version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      github-actions:
        patterns:
          - "*"
    open-pull-requests-limit: 5
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: monthly
    groups:
      maven-framework-libraries:
        patterns:
          - "org.seleniumhq.selenium:*"
          - "org.testng:*"
          - "io.qameta.allure:*"
          - "org.assertj:*"
          - "org.apache.logging.log4j:*"
          - "org.slf4j:*"
          - "org.aspectj:*"
          - "org.projectlombok:*"
      maven-build-plugins:
        patterns:
          - "org.apache.maven.plugins:*"
          - "com.diffplug.spotless:*"
          - "com.github.spotbugs:*"
          - "org.cyclonedx:*"
    open-pull-requests-limit: 5
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: monthly
    groups:
      selenium-grid-images:
        patterns:
          - "selenium/*"
    open-pull-requests-limit: 5
